{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.vickypathak123",
    "module": "Integrity-Check",
    "version": "1.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "Integrity-Check-1.1.0.aar",
          "url": "Integrity-Check-1.1.0.aar",
          "size": 41804,
          "sha512": "9222d3e314c571c7e9061fe9cd738d2c5d7fc3037beea62ba4168e3626a6efa4e5ad11dc10f541fa814730ad79dce3c87a181251417a6125750c679ed2a4aa31",
          "sha256": "f97e92e4e9a23b52cc9ca084dc26e6a44ccc07df059f2d88a944ae938bb8eff9",
          "sha1": "727840bc38ce69a48d4d5bea5406f1cc72d1f22b",
          "md5": "fcff3f41c139ae0ce3977797954490e2"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.12.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-base",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "com.google.android.play",
          "module": "integrity",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.apis",
          "module": "google-api-services-playintegrity",
          "version": {
            "requires": "v1-rev20231109-2.0.0"
          },
          "excludes": [
            {
              "group": "com.google.guava",
              "module": "guava"
            }
          ]
        },
        {
          "group": "com.google.api-client",
          "module": "google-api-client-jackson2",
          "version": {
            "requires": "1.20.0"
          }
        },
        {
          "group": "com.google.auth",
          "module": "google-auth-library-credentials",
          "version": {
            "requires": "1.20.0"
          }
        },
        {
          "group": "com.google.auth",
          "module": "google-auth-library-oauth2-http",
          "version": {
            "requires": "1.20.0"
          }
        },
        {
          "group": "com.google.android.ump",
          "module": "user-messaging-platform",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "Integrity-Check-1.1.0.aar",
          "url": "Integrity-Check-1.1.0.aar",
          "size": 41804,
          "sha512": "9222d3e314c571c7e9061fe9cd738d2c5d7fc3037beea62ba4168e3626a6efa4e5ad11dc10f541fa814730ad79dce3c87a181251417a6125750c679ed2a4aa31",
          "sha256": "f97e92e4e9a23b52cc9ca084dc26e6a44ccc07df059f2d88a944ae938bb8eff9",
          "sha1": "727840bc38ce69a48d4d5bea5406f1cc72d1f22b",
          "md5": "fcff3f41c139ae0ce3977797954490e2"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "Integrity-Check-1.1.0-sources.jar",
          "url": "Integrity-Check-1.1.0-sources.jar",
          "size": 14125,
          "sha512": "be3c81633aface659905804a44b9d873c99e40748459f7df60e8bc9203e1796fe1915fdc04764e4bdc9c248111c1e6b86161ba80b48e7b9f61e723dd53902871",
          "sha256": "d473b5522d964fff35b985977513d1d59297e2ff38a63500165b46547fe500be",
          "sha1": "cd0cebe9fef1db8cc282510f28f72d61b75c9768",
          "md5": "e2c36894e2a79ec1e0ea8d6e40b63581"
        }
      ]
    }
  ]
}
